[project]
name = "fullstack-webapp"
version = "1.0.0"

# Frontend Dependencies (JavaScript/TypeScript)
[dependencies.javascript]
react = "^18.2.0"
react-dom = "^18.2.0"
react-router-dom = "^6.8.0"
axios = "^1.3.0"

[dev-dependencies.javascript]
"@types/react" = "^18.0.0"
"@types/react-dom" = "^18.0.0"
"@vitejs/plugin-react" = "^3.1.0"
typescript = "^4.9.0"
vite = "^4.1.0"
eslint = "^8.35.0"
"@typescript-eslint/eslint-plugin" = "^5.54.0"
"@typescript-eslint/parser" = "^5.54.0"
prettier = "^2.8.0"
jest = "^29.4.0"
"@testing-library/react" = "^14.0.0"
"@testing-library/jest-dom" = "^5.16.0"

# Backend Dependencies (Python)
[dependencies.python]
flask = "^2.2.0"
flask-cors = "^3.0.0"
flask-migrate = "^4.0.0"
sqlalchemy = "^2.0.0"
python-dotenv = "^1.0.0"

[dev-dependencies.python]
pytest = "^7.2.0"
pytest-flask = "^1.2.0"
black = "^23.1.0"
flake8 = "^6.0.0"
coverage = "^7.1.0"

# Project Scripts
[scripts]
# Development
dev = "concurrently \"ppm run frontend:dev\" \"ppm run backend:dev\""
frontend:dev = "cd frontend && vite"
backend:dev = "cd backend && flask run --debug"

# Production
build = "cd frontend && vite build && cd ../backend && python -m pip freeze > requirements.txt"
start = "cd backend && gunicorn app:app"

# Testing
test = "ppm run frontend:test && ppm run backend:test"
frontend:test = "cd frontend && jest"
backend:test = "cd backend && python -m pytest"
test:coverage = "cd frontend && jest --coverage && cd ../backend && coverage run -m pytest && coverage report"

# Code Quality
lint = "cd frontend && eslint src --ext .ts,.tsx && cd ../backend && flake8 ."
format = "cd frontend && prettier --write src && cd ../backend && black ."

# Database
db:migrate = "cd backend && flask db upgrade"
db:seed = "cd backend && python scripts/seed_db.py"

# Virtual Environment Configuration
[venv]
python = "python3.11"
path = ".venv"
